version: '2.1'

services:
  mongo-client:
    build: ./
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb


  mongodb:
    image: mongo:3.6.9
    container_name: mongo-db
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles